parameters:
#    user_profesional.example.class: User\ProfesionalBundle\Example

services:
#    user_profesional.example:
#        class: %user_profesional.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
