<?php

namespace Core\FileServerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{

    public function retrieveUserFiles($user){

    }

    public function retrieveUserFilesAccess(\Core\UserBundle\Entity\User $user){
        $qb = $this->getEntityManager()
            ->createQuery("SELECT p, f FROM CoreFileServerBundle:Permissions p LEFT JOIN p.file f WHERE p.user = :user AND p.permission >= :permissions")
            ->setParameter('user', $user->getId())
            ->setParameter('permissions', 4);

        $result = $qb->getResult();


        $return = array();

        foreach($result as $r){
            array_push($return, $r->getFile());
        }

        return $return;
    }
}
