security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CLIENTE: ROLE_USER
        ROLE_COLLABORATOR: ROLE_USER
        ROLE_PROFESIONAL: [ ROLE_USER, ROLE_COLLABORATOR, ROLE_CLIENTE ]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            oauth:
                resource_owners:
                    linkedin: "/login/check-linkedin"
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                     service: my_user_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/acceso$, role: ROLE_USER }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profesional/, role: ROLE_PROFESIONAL }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/collaborator/, role: ROLE_COLABORATOR }
        - { path: ^/client/, role: ROLE_CLIENTE }