parameters:
#    core_user.example.class: Core\UserBundle\Example

services:
#    core_user.example:
#        class: %core_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
parameters:
    my_user_provider.class: Core\UserBundle\Provider\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,@doctrine.orm.default_entity_manager,{linkedin: linkedin_id}]