parameters:
#    user_collaborator.example.class: User\CollaboratorBundle\Example

services:
#    user_collaborator.example:
#        class: %user_collaborator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
