parameters:
#    user_guess.example.class: User\GuessBundle\Example

services:
#    user_guess.example:
#        class: %user_guess.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
